/**
 * Represents a stored form submission.
 */
export interface Submission {
    /**
     * Unique identifier for the submission.
     * Generated by PostgreSQL using gen_random_uuid().
     */
    id: string;

    /**
     * ID of the form this submission belongs to.
     * References forms(id).
     */
    form_id: string;

    /**
     * IP address of the client submitting the form.
     * Stored as PostgreSQL INET.
     */
    ip_address: string | null;

    /**
     * Parsed payload extracted from the request body.
     * Contains primitive values or arrays from the form submission.
     */
    payload: Record<string, unknown> | null;

    /**
     * Raw request body captured from the incoming request.
     * Useful for debugging or reparsing.
     */
    raw_body: string | null;

    /**
     * Raw request headers serialized as text.
     */
    raw_headers: Record<string, string | null> | null;

    /**
     * Spam detection score.
     * 0 = clean, higher values indicate higher spam likelihood.
     */
    spam_score: number;

    /**
     * List of reasons explaining why the submission was flagged.
     * Example: ["honeypot", "rate_limit"].
     */
    spam_reasons: string[] | null;

    /**
     * Timestamp when spam detection was last performed.
     */
    spam_checked_at: string | null;

    /**
     * Time when the submission was created.
     */
    created_at: string;
}
